# questions.py
# All question pools for Jennie Bot


# ==============================
# FUN QUESTIONS
# ==============================

FUN_QUESTIONS = [
   "What’s something small that made you smile recently?",
   "How do you usually spend a free evening?",
   "Are you more of a morning person or a night owl?",
   "What’s your go-to comfort food?",
   "What’s a simple thing you enjoy more than most people?",
   "What’s a hobby you enjoy or want to get into?",
   "What kind of music do you usually listen to?",
   "What’s a show or movie you’d recommend right now?",
   "Do you prefer staying in or going out on weekends?",
   "What’s something you’re surprisingly good at?",
   "What’s something small that instantly improves your mood?",
   "What’s a movie you could watch more than once and still enjoy?",
   "What’s your go-to way to unwind after a long day?",
   "What’s a song you always end up singing along to?",
   "What’s a hobby you’ve been curious about but haven’t tried yet?",
   "What’s the best meal you’ve had recently?",
   "What’s a place you enjoy wandering around without a plan?",
   "What’s something you’re looking forward to right now?",
   "What’s a food you’ll never get tired of?",
   "What’s a simple pleasure you never get bored of?",
   "What’s your favourite way to spend a free afternoon?",
   "What’s a sound that instantly relaxes you?",
   "What’s something you enjoy doing alone?",
   "What’s a habit you’re glad you picked up?",
   "What’s your favourite way to waste time?",
   "What’s a playlist or genre you always return to?",
   "What’s something small you enjoy that others might overlook?",
   "What’s a fun memory that always makes you smile?",
   "What’s a random thing that makes you nostalgic?",
   "What’s a place you’d visit again without thinking twice?",
   "What’s a fun fact about yourself?",
   "What’s something you’re oddly proud of?",
   "What’s a routine you secretly enjoy?",
   "What’s a show or movie you think is underrated?",
   "What’s a simple thing that makes a bad day better?",
   "What’s something that makes time fly for you?",
   "What’s your favourite type of weather?",
   "What’s a skill you’d love to learn someday?",
   "What’s a harmless opinion you’ll defend forever?",
   "What’s a small tradition you enjoy?",
   "What’s a movie or show you quote way too often?",
   "What’s a place that always feels comforting to you?",
   "What’s something you enjoy but rarely talk about?",
   "What’s a fun goal you have right now?",
   "What’s a sound or smell you really like?",
   "What’s something you learned recently that surprised you?",
   "What’s the best way to spend a lazy day?",
   "What’s a hobby you didn’t expect to enjoy but do?",
   "What’s a random app you use more than you should?",
   "What’s a snack you always keep around?",
   "What’s a topic you could talk about for hours?",
   "What’s something that instantly makes you laugh?",
   "What’s a daily moment you quietly look forward to?",
   "What’s a movie or show you find comforting?",
   "What’s a small habit that improves your mood?",
   "What’s something that makes ordinary days better?",
   "If you could instantly master one skill, what would it be?",
   "What’s a food you could eat every week and not get bored of?",
   "What’s a place you enjoy going back to?",
   "What’s a small routine you actually enjoy?",
   "What’s something you’re currently looking forward to?",
   "What’s something you learned recently?",
   "What’s a simple pleasure you don’t get tired of?",
   "What’s something that helps you relax?",
   "If you could spend a day anywhere, where would it be?",
   "What kind of weather puts you in the best mood?",
   "If you had a totally free day tomorrow, how would you spend it?",
   "What’s a skill you’d like to learn someday?",
   "What’s something people don’t usually ask you about?",
   "What’s something you appreciate more as you get older?",
   "What’s a simple way you like to unwind?",
   "What’s a snack you always enjoy?",
   "What’s a topic you’re curious about lately?",
   "What’s a quiet moment you look forward to each day?"
]


# ==============================
# WOULD YOU RATHER
# ==============================

WOULD_YOU_RATHER = [
   "Would you rather always be early or always be late?",
   "Would you rather travel the world for free or live in your dream city?",
   "Would you rather give up music or movies?",
   "Would you rather work four long days or five short days?",
   "Would you rather never use social media again or never watch TV again?",
   "Would you rather explore space or the deep ocean?",
   "Would you rather have unlimited free time or unlimited money?",
   "Would you rather live near the ocean or in the mountains?",
   "Would you rather always know the truth or always be happy?",
   "Would you rather be great at one thing or decent at many things?",
   "Would you rather cook every meal or never cook again?",
   "Would you rather read minds or see the future?",
   "Would you rather lose your phone or your wallet?",
   "Would you rather be famous or live a private life?",
   "Would you rather work from home or work in an office?",
   "Would you rather always have perfect weather or perfect timing?",
   "Would you rather live without music or without movies?",
   "Would you rather always have to whisper or always shout?",
   "Would you rather never feel tired or never feel stressed?",
   "Would you rather travel alone or with friends?",
   "Would you rather have more time or more energy?",
   "Would you rather be incredibly creative or incredibly logical?",
   "Would you rather always find parking or never wait in line?",
   "Would you rather live in the past or the future?",
   "Would you rather be able to fly or teleport?",
   "Would you rather know how people see you or never know at all?",
   "Would you rather always say what you think or always think before speaking?",
   "Would you rather have a calm life or an exciting life?",
   "Would you rather always win arguments or always avoid them?",
   "Would you rather explore a new hobby every year or master one hobby?",
   "Would you rather live without coffee or without snacks?",
   "Would you rather always be busy or always be bored?",
   "Would you rather never need sleep or always wake up refreshed?",
   "Would you rather live in a small town or a big city?",
   "Would you rather have a perfect memory or forget bad moments easily?",
   "Would you rather be great at planning or great at improvising?",
   "Would you rather never feel awkward or never feel embarrassed?",
   "Would you rather always know when someone is lying or never know?",
   "Would you rather work for passion or for comfort?",
   "Would you rather be spontaneous or well-prepared?",
   "Would you rather always have good luck or good timing?",
   "Would you rather never run out of battery or never lose internet?",
   "Would you rather be able to pause time or rewind time?",
   "Would you rather be known for kindness or intelligence?",
   "Would you rather explore new places or revisit favourite ones?",
   "Would you rather have more confidence or more patience?",
   "Would you rather live simply or live luxuriously?",
   "Would you rather always be learning or always be teaching?",
   "Would you rather have endless curiosity or endless focus?",
   "Would you rather work alone or in a team?",
   "Would you rather have fewer close friends or many casual ones?",
   "Would you rather be great at starting things or finishing them?",
   "Would you rather live near family or far away?",
   "Would you rather have your dream job or dream lifestyle?",
   "Would you rather always feel motivated or always feel relaxed?",
   "Would you rather be remembered for what you did or who you were?",
   "Would you rather always find inspiration or always find peace?",
   "Would you rather have a flexible schedule or a fixed routine?",
   "Would you rather live in a quiet place or a lively one?",
   "Would you rather have clarity or creativity?",
   "Would you rather be very organised or very adaptable?",
   "Would you rather take risks or play it safe?",
   "Would you rather live fast or live thoughtfully?",
   "Would you rather always feel curious or always feel content?",
   "Would you rather have more experiences or more stability?",
   "Would you rather travel often or settle early?",
   "Would you rather lead or support?",
   "Would you rather live without plans or without surprises?",
   "Would you rather be patient or decisive?",
   "Would you rather be known or unknown?",
   "Would you rather have a long career or a fulfilling one?",
   "Would you rather work harder now or later?",
   "Would you rather explore ideas or explore places?",
   "Would you rather always be calm or always be excited?",
   "Would you rather live slowly or live intensely?",
   "Would you rather always feel inspired or always feel secure?",
   "Would you rather have control or freedom?",
   "Would you rather build something new or improve something old?",
   "Would you rather trust easily or carefully?",
   "Would you rather live with structure or flexibility?",
   "Would you rather chase goals or enjoy the journey?",
   "Would you rather have variety or consistency?",
   "Would you rather think deeply or act quickly?",
   "Would you rather live for moments or for meaning?"
]


# ==============================
# NEVER HAVE I EVER
# ==============================

NEVER_HAVE_I_EVER = [
   "Never have I ever missed an important message and pretended I didn’t see it.",
   "Never have I ever stayed up way too late watching something random.",
   "Never have I ever googled something I was too embarrassed to ask.",
   "Never have I ever rewatched the same show just for comfort.",
   "Never have I ever forgotten why I opened an app.",
   "Never have I ever laughed at something I didn’t fully understand.",
   "Never have I ever cancelled plans and felt relieved.",
   "Never have I ever said ‘I’m on the way’ when I wasn’t.",
   "Never have I ever overthought a simple message.",
   "Never have I ever checked the fridge multiple times hoping something new appeared.",
   "Never have I ever judged a movie by its trailer.",
   "Never have I ever ignored a call and texted later.",
   "Never have I ever taken a screenshot and forgotten about it.",
   "Never have I ever fallen asleep during a movie.",
   "Never have I ever Googled myself.",
   "Never have I ever procrastinated something important.",
   "Never have I ever felt productive without actually doing much.",
   "Never have I ever forgotten someone’s name right after meeting them.",
   "Never have I ever replayed a conversation in my head.",
   "Never have I ever laughed at my own joke.",
   "Never have I ever planned to be productive and did nothing.",
   "Never have I ever been late because I underestimated time.",
   "Never have I ever eaten snacks meant for later.",
   "Never have I ever started something and never finished it.",
   "Never have I ever said ‘just five more minutes’.",
   "Never have I ever avoided eye contact in public.",
   "Never have I ever scrolled endlessly without realizing time passed.",
   "Never have I ever forgotten where I put my phone while holding it.",
   "Never have I ever pretended to listen while thinking of something else.",
   "Never have I ever laughed at a meme more than once.",
   "Never have I ever re-read an old message for no reason.",
   "Never have I ever searched reviews before buying something small.",
   "Never have I ever felt tired without doing anything.",
   "Never have I ever made a to-do list and ignored it.",
   "Never have I ever opened a notification and forgot why.",
   "Never have I ever checked the time repeatedly.",
   "Never have I ever wanted a nap right after waking up.",
   "Never have I ever started a new habit enthusiastically then dropped it.",
   "Never have I ever replayed a song on loop.",
   "Never have I ever felt hungry but didn’t know what to eat.",
   "Never have I ever taken longer to choose something simple.",
   "Never have I ever saved something to read later and never did.",
   "Never have I ever felt accomplished after doing something small.",
   "Never have I ever avoided making a decision.",
   "Never have I ever opened multiple tabs and forgotten why.",
   "Never have I ever felt nostalgic for something random.",
   "Never have I ever laughed quietly to myself in public.",
   "Never have I ever wanted to skip a task and reward myself anyway.",
   "Never have I ever spent too long choosing what to watch.",
   "Never have I ever checked my phone without notifications.",
   "Never have I ever felt productive organizing instead of doing.",
   "Never have I ever forgotten what day it was.",
   "Never have I ever said ‘I’ll do it tomorrow’.",
   "Never have I ever enjoyed doing nothing.",
   "Never have I ever delayed replying even though I saw the message.",
   "Never have I ever felt busy without being productive.",
   "Never have I ever Googled something just out of curiosity.",
   "Never have I ever lost track of time scrolling.",
   "Never have I ever re-read something because I zoned out.",
   "Never have I ever made plans and wished they’d cancel.",
   "Never have I ever felt happy for no clear reason.",
   "Never have I ever procrastinated by cleaning.",
   "Never have I ever felt relieved when plans got postponed.",
   "Never have I ever forgotten an idea I thought was great.",
   "Never have I ever checked the fridge out of boredom.",
   "Never have I ever laughed at a joke late.",
   "Never have I ever overthought a decision that didn’t matter.",
   "Never have I ever felt productive just checking things off.",
   "Never have I ever reloaded an app without reason.",
   "Never have I ever delayed starting something important.",
   "Never have I ever enjoyed a quiet moment unexpectedly.",
   "Never have I ever wanted time to slow down.",
   "Never have I ever wanted time to speed up.",
   "Never have I ever gotten distracted mid-task.",
   "Never have I ever made a mental to-do list.",
   "Never have I ever enjoyed a simple routine.",
   "Never have I ever felt calm doing something repetitive.",
   "Never have I ever ignored a notification intentionally.",
   "Never have I ever thought ‘I deserve a break’ before starting.",
   "Never have I ever felt proud of finishing something small.",
   "Never have I ever delayed a decision hoping it resolves itself.",
   "Never have I ever enjoyed background noise while doing nothing."
]


# ==============================
# SITUATION DILEMMA (DRAW 5)
# ==============================

SITUATION_DILEMMA = [
"You discover a close friend is cheating in an exam that will decide their future. Do you stay silent or intervene?",
   "You’re offered a promotion that requires relocating, but it will seriously affect your family life. What do you prioritize?",
   "A colleague takes credit for your idea, and your manager praises them. Do you confront them or let it go?",
   "You find out your best employee is great at work but toxic to the team. Do you keep performance or protect culture?",
   "You overhear a private conversation that reveals a truth you were never meant to know. Do you act on it?",
   "A friend asks for honest feedback about something they’re proud of, but you genuinely dislike it. What do you say?",
   "You can help one person significantly or help many people a little. Which do you choose?",
   "You notice a small but serious mistake that no one else has caught and fixing it will delay the entire project. What do you do?",
   "A family member asks you to lie on their behalf for something non-illegal but unethical. Do you agree?",
   "You’re offered more money for a job you dislike or less money for one you enjoy. How do you decide?",


   "You learn confidential information that could hurt someone if revealed but protect others if shared. What do you do?",
   "A friend constantly asks for emotional support but never shows up for you. Do you confront or distance yourself?",
   "You can expose a wrongdoing, but it will damage people who were not involved. Do you proceed?",
   "A manager asks you to do something technically allowed but morally uncomfortable. How do you respond?",
   "You find out your success depends partly on someone else failing. Do you feel responsible?",
   "You must choose between being honest and keeping peace in a relationship. Which matters more?",
   "You can correct someone publicly and embarrass them or stay quiet and let misinformation spread. What’s better?",
   "You’re given credit for something you didn’t fully earn. Do you clarify or accept it?",
   "You realize a long-held belief you have is wrong but admitting it would cost you respect. Do you change publicly?",
   "A friend is making a life decision you strongly disagree with. Do you intervene or respect their choice?",


   "You have limited resources and must choose who gets help first. What factors matter most?",
   "You’re asked to choose loyalty to a person or loyalty to your principles. How do you decide?",
   "You find out someone you admire achieved success through questionable means. Does it change how you see them?",
   "You can prevent a small injustice now or a larger injustice later, but not both. What do you pick?",
   "You’re rewarded for silence. Speaking up would cost you personally but help others. What do you do?",
   "A friend asks for advice but repeatedly ignores it and complains. Do you keep helping?",
   "You discover a mistake you made years ago that never surfaced. Do you bring it up now?",
   "You must choose between fairness and compassion in a difficult decision. Which comes first?",
   "You’re forced to make a decision without all the information. How do you proceed?",
   "You realize helping someone will make them dependent on you long-term. Do you still help?",


   "You must choose between personal growth and stability. What guides your decision?",
   "A relationship is comfortable but no longer inspiring. Do you value comfort or change?",
   "You witness behavior that’s not illegal but clearly harmful. Do you step in?",
   "You can protect someone’s feelings or tell a truth that will hurt but help long-term. Which do you choose?",
   "You’re offered success at the cost of your privacy. Is it worth it?",
   "You notice unequal treatment but speaking up may backfire. Do you act?",
   "You must choose between being liked and being respected. Which matters more?",
   "A rule exists for good reasons, but breaking it would help someone immediately. Do you break it?",
   "You’re asked to forgive without receiving an apology. Do you?",
   "You can avoid conflict by staying quiet, but it reinforces a bad pattern. What do you do?",


   "You realize your silence benefits you but harms others indirectly. Are you responsible?",
   "You’re given a second chance that others didn’t receive. Do you feel guilty?",
   "You must choose between honesty and loyalty. Can both exist together?",
   "You see potential in someone who keeps self-sabotaging. How much responsibility do you take?",
   "You’re pressured to choose sides in a conflict where both are partly wrong. What do you do?",
   "You’re asked to make a decision that benefits the group but harms one individual. Is it justified?",
   "You can step in to help, but no one asked you to. Do you interfere?",
   "You realize your success depends on a system you disagree with. Do you continue?",
   "You must decide quickly with long-term consequences. How do you prioritize?",
   "You’re offered clarity but at the cost of someone else’s privacy. Do you accept?",


   "You must choose between consistency and growth when they conflict. Which wins?",
   "You can be kind or be honest, but not both in the moment. What do you choose?",
   "You’re asked to lead without authority. How do you approach it?",
   "You notice you benefit from unfair advantages you didn’t create. Do you address it?",
   "You’re forced to choose between two people you care about. How do you decide?",
   "You can wait for the perfect moment or act now imperfectly. Which do you pick?",
   "You realize your opinion influences others more than you expected. Do you pull back?",
   "You’re given power without accountability. How do you use it?",
   "You must choose between short-term peace and long-term stability. What matters more?",
   "You discover a truth that changes how you see someone close to you. Do you confront them?",


   "You can protect your image or do what you believe is right. Which do you choose?",
   "You’re asked to take responsibility for something you didn’t directly cause. Do you accept?",
   "You must choose between efficiency and empathy. Which guides your decision?",
   "You realize staying neutral benefits the stronger side. Is neutrality still ethical?",
   "You’re offered forgiveness but only if you stop asking questions. Do you accept?",
   "You can influence a decision quietly or oppose it openly. Which is better?",
   "You’re asked to compromise a value ‘just this once’. Is that acceptable?",
   "You notice people follow your behavior more than your words. Do you change how you act?",
   "You can end a conflict by taking blame you don’t deserve. Do you do it?",
   "You must decide without knowing whether your choice will be appreciated or criticized."



]


# ==============================
# RED / GREEN FLAG
# ==============================

RED_GREEN_FLAG = [
"They never post on social media. Red flag or green flag?",
   "They are very close to their parents as an adult. Red flag or green flag?",
   "They avoid talking about past relationships. Red flag or green flag?",
   "They are extremely career-focused and often busy. Red flag or green flag?",
   "They prefer staying in rather than going out most weekends. Red flag or green flag?",
   "They don’t like texting and prefer calls or in-person talks. Red flag or green flag?",
   "They believe finances should be kept separate in a relationship. Red flag or green flag?",
   "They don’t have many close friends. Red flag or green flag?",
   "They are friends with most of their exes. Red flag or green flag?",
   "They hate talking about emotions and feelings. Red flag or green flag?",


   "They are very protective of their personal space and alone time. Red flag or green flag?",
   "They don’t celebrate birthdays or anniversaries. Red flag or green flag?",
   "They avoid conflict at all costs. Red flag or green flag?",
   "They are brutally honest, even when it hurts. Red flag or green flag?",
   "They don’t believe in traditional marriage. Red flag or green flag?",
   "They prefer planning everything in advance. Red flag or green flag?",
   "They believe love should feel calm, not intense. Red flag or green flag?",
   "They don’t like sharing passwords or devices. Red flag or green flag?",
   "They rarely ask for help. Red flag or green flag?",
   "They are very private about their family. Red flag or green flag?",


   "They believe money arguments are inevitable in relationships. Red flag or green flag?",
   "They don’t enjoy group gatherings and prefer one-on-one interactions. Red flag or green flag?",
   "They are highly independent and dislike relying on others. Red flag or green flag?",
   "They don’t talk much during arguments and go silent instead. Red flag or green flag?",
   "They value loyalty over honesty. Red flag or green flag?",
   "They are extremely cautious before trusting people. Red flag or green flag?",
   "They believe relationships require constant effort. Red flag or green flag?",
   "They don’t like mixing friend groups. Red flag or green flag?",
   "They prioritize financial security over passion. Red flag or green flag?",
   "They believe love should grow slowly. Red flag or green flag?",


   "They don’t post their partner online. Red flag or green flag?",
   "They are uncomfortable discussing future plans. Red flag or green flag?",
   "They believe everyone should pay their own way. Red flag or green flag?",
   "They dislike public displays of affection. Red flag or green flag?",
   "They prefer routines over spontaneity. Red flag or green flag?",
   "They value peace over being right. Red flag or green flag?",
   "They don’t believe people change much. Red flag or green flag?",
   "They are very selective about who they let close. Red flag or green flag?",
   "They think love alone isn’t enough for marriage. Red flag or green flag?",
   "They don’t like discussing money early in dating. Red flag or green flag?",


   "They believe arguments are healthy if handled well. Red flag or green flag?",
   "They prefer emotional stability over excitement. Red flag or green flag?",
   "They are cautious about moving in together. Red flag or green flag?",
   "They believe personal growth matters more than relationship comfort. Red flag or green flag?",
   "They don’t enjoy sharing every detail of their day. Red flag or green flag?",
   "They dislike labels early on. Red flag or green flag?",
   "They value respect more than romance. Red flag or green flag?",
   "They believe relationships should add to life, not complete it. Red flag or green flag?",
   "They don’t believe in soulmates. Red flag or green flag?",
   "They prefer solving problems quietly rather than discussing them openly. Red flag or green flag?",


   "They are careful with spending even when they can afford more. Red flag or green flag?",
   "They believe marriage changes relationships negatively. Red flag or green flag?",
   "They prioritize mental health over relationship expectations. Red flag or green flag?",
   "They don’t enjoy surprises. Red flag or green flag?",
   "They believe love should feel safe, not dramatic. Red flag or green flag?",
   "They don’t believe jealousy is a sign of love. Red flag or green flag?",
   "They are slow to commit but consistent once they do. Red flag or green flag?",
   "They prefer deep conversations over constant communication. Red flag or green flag?",
   "They don’t believe partners need to share all interests. Red flag or green flag?",
   "They think space strengthens relationships. Red flag or green flag?",


   "They believe financial compatibility is more important than chemistry. Red flag or green flag?",
   "They don’t enjoy talking about childhood or family history. Red flag or green flag?",
   "They believe love should be practical. Red flag or green flag?",
   "They don’t rush emotional intimacy. Red flag or green flag?",
   "They prefer quality time over frequent contact. Red flag or green flag?",
   "They think marriage involves compromise more than romance. Red flag or green flag?",
   "They don’t believe in sharing everything with a partner. Red flag or green flag?",
   "They value long-term stability over short-term happiness. Red flag or green flag?",
   "They believe independence is essential in love. Red flag or green flag?",
   "They think relationships should feel peaceful most of the time. Red flag or green flag?"



]


# ==============================
# HOT TAKES (100+ · DRAW 8)
# ==============================

HOT_TAKES = [
"Working from home is overrated.",
    "Money matters more than passion in the long run.",
    "Most people confuse being busy with being productive.",
    "Comfort is more dangerous than failure.",
    "Social media has made people less social.",
    "Consistency is more important than motivation.",
    "Talent matters less than discipline.",
    "Being alone is underrated.",
    "Most people don’t actually want advice, just validation.",
    "Stability is more attractive than excitement.",

    "Hard work doesn’t always pay off.",
    "People romanticize being broke too much.",
    "Peace is better than being right.",
    "Growth often feels like loss at first.",
    "Being honest is harder than being kind.",
    "Confidence is more attractive than looks.",
    "Most arguments are about ego, not truth.",
    "Overthinking ruins more opportunities than failure.",
    "Comfort zones shrink your world.",
    "Timing matters more than talent.",

    "Independence is more important than loyalty.",
    "Love alone isn’t enough to sustain a relationship.",
    "People change less than they think.",
    "Ambition can ruin relationships.",
    "Being calm is a superpower.",
    "Success isolates people.",
    "Privacy is more valuable than attention.",
    "Trust should be earned slowly.",
    "Being liked is overrated.",
    "Boundaries are more important than apologies.",

    "Most people are bad at listening.",
    "Silence is often misunderstood.",
    "Having options makes decisions harder.",
    "Stability is a form of privilege.",
    "Emotional intelligence matters more than IQ.",
    "Consistency beats intensity.",
    "Freedom is scary for most people.",
    "Being alone doesn’t mean being lonely.",
    "People confuse attraction with compatibility.",
    "Respect lasts longer than romance.",

    "Burnout is often self-inflicted.",
    "People stay in situations longer than they should.",
    "Discipline creates freedom.",
    "Being realistic is often mistaken for being negative.",
    "Most people avoid difficult conversations.",
    "Clarity is more attractive than charm.",
    "Not everyone deserves access to you.",
    "Being misunderstood is part of growth.",
    "Self-awareness is rare.",
    "People romanticize hustle too much.",

    "Change is uncomfortable because it works.",
    "Emotional safety matters more than excitement.",
    "Being direct saves time and relationships.",
    "Most people fear judgment more than failure.",
    "Growth requires letting people down.",
    "Saying no is a form of self-respect.",
    "Comfort kills ambition.",
    "People confuse confidence with arrogance.",
    "Consistency is boring but effective.",
    "Longevity matters more than intensity.",

    "Most people don’t actually know what they want.",
    "Being needed is not the same as being loved.",
    "Avoiding conflict creates bigger problems.",
    "Personal growth often feels lonely.",
    "Effort matters more than talent.",
    "People overestimate motivation and underestimate habits.",
    "Being busy is not impressive.",
    "Self-control is more attractive than self-expression.",
    "Security is underrated.",
    "Trust is built in small moments.",

    "Most people are afraid of being seen.",
    "Freedom requires responsibility.",
    "Being calm is a competitive advantage.",
    "People romanticize chaos.",
    "Stability creates space for creativity.",
    "Listening is more powerful than speaking.",
    "Growth requires discomfort.",
    "Being selective is a form of self-care.",
    "Not every opinion needs to be shared.",
    "Peace is addictive once you taste it.",

    "Most people avoid accountability.",
    "Being consistent is harder than being talented.",
    "Discipline outlasts motivation.",
    "Clarity reduces anxiety.",
    "People mistake intensity for depth.",
    "Growth often costs relationships.",
    "Being alone helps you hear yourself.",
    "Most people fear being ordinary.",
    "Patience is a lost skill.",
    "Stability is not boring if you value peace."
]


# ==============================
# FINISH THE SENTENCE (80 · DRAW 5)
# ==============================

FINISH_THE_SENTENCE = [
"Lately, I’ve been thinking a lot about ___.",
    "Right now, I’m trying to get better at ___.",
    "One thing I’m proud of but rarely say out loud is ___.",
    "These days, I value ___ more than I used to.",
    "A habit I’m trying to build is ___.",

    "Something that helps me reset mentally is ___.",
    "I feel most confident when ___.",
    "A small thing that makes my day better is ___.",
    "Recently, I’ve realized that ___.",
    "One thing I want more of in my life is ___.",

    "I feel most like myself when ___.",
    "A boundary I’ve learned to set is ___.",
    "One thing I’ve outgrown is ___.",
    "I’m currently learning how to ___.",
    "A decision that changed me was ___.",

    "Right now, I’m grateful for ___.",
    "A place that helps me feel calm is ___.",
    "Something I don’t stress about anymore is ___.",
    "A lesson I keep relearning is ___.",
    "One thing I’m working on letting go of is ___.",

    "I feel recharged after ___.",
    "A mindset I’m trying to adopt is ___.",
    "One thing I want to protect more is ___.",
    "I’ve become more aware of ___ lately.",
    "A simple thing I enjoy more than expected is ___.",

    "I feel most relaxed when ___.",
    "Something I’ve changed my mind about is ___.",
    "A routine that helps me stay grounded is ___.",
    "One thing I want to be more consistent with is ___.",
    "Lately, I’ve been prioritizing ___ over ___.",

    "I feel most focused when ___.",
    "A quality I appreciate more now is ___.",
    "Something that motivates me right now is ___.",
    "A habit I’m trying to reduce is ___.",
    "One thing I’ve learned to accept is ___.",

    "I feel proud of myself when ___.",
    "A small win I had recently was ___.",
    "Something I’m curious about these days is ___.",
    "I feel most present when ___.",
    "One thing I want to improve this year is ___.",

    "A mindset that has helped me lately is ___.",
    "I feel most comfortable when ___.",
    "Something I’m slowly getting better at is ___.",
    "One thing I want to do more intentionally is ___.",
    "Lately, I’ve been paying more attention to ___.",

    "I feel most balanced when ___.",
    "A habit I’m glad I picked up is ___.",
    "Something I value more now than before is ___.",
    "One thing I want to simplify in my life is ___.",
    "I feel most at ease when ___.",

    "A change I’m open to right now is ___.",
    "Something I’m learning to be patient with is ___.",
    "I feel most energized when ___.",
    "One thing I want to be better at communicating is ___.",
    "Lately, I’ve been more mindful of ___.",

    "A personal rule I try to follow is ___.",
    "I feel most satisfied at the end of a day when ___.",
    "One thing I want to invest more time in is ___.",
    "Something I’m more confident about now is ___.",
    "I feel most grounded when ___.",

    "A belief I’m questioning lately is ___.",
    "One thing I want to protect my energy from is ___.",
    "I feel most clear-headed when ___.",
    "Something I want to be remembered for is ___.",
    "Right now, I’m focused on ___."
]
